version: 2

sources:
    - name: dbt_quickstartguide
      description: This is a replica of the Postgres database used by our app
      database: VITS_TEST_DB
      schema: raw_jaffle_shop
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.